require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/MutableConstant:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 130

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Metrics:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertTruthy:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false
