AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
